INSERT INTO stories (
    id,
    slug,
    title,
    cover_image_url,
    author_name,
    short_description,
    story_status,
    total_chapters,
    is_hot,
    is_recommended,
    recommended_at,
    view_count,
    like_count,
    created_at,
    updated_at,
    published_at
)
VALUES
    (
        gen_random_uuid(),
        'the-shadow-scribe',
        'The Shadow Scribe',
        'https://cdn.example.com/covers/the-shadow-scribe.jpg',
        'An Tran',
        'A quiet archivist discovers a living manuscript that rewrites fate.',
        'ONGOING',
        56,
        true,
        true,
        now() - interval '3 days',
        125000,
        4200,
        now() - interval '60 days',
        now() - interval '1 days',
        now() - interval '55 days'
    ),
    (
        gen_random_uuid(),
        'iron-lotus-oath',
        'Iron Lotus Oath',
        'https://cdn.example.com/covers/iron-lotus-oath.jpg',
        'Minh Le',
        'A warrior bound to a sacred lotus must choose between duty and love.',
        'ONGOING',
        72,
        true,
        false,
        null,
        98000,
        3100,
        now() - interval '90 days',
        now() - interval '2 days',
        now() - interval '88 days'
    ),
    (
        gen_random_uuid(),
        'midnight-archive',
        'Midnight Archive',
        'https://cdn.example.com/covers/midnight-archive.jpg',
        'Linh Dao',
        'A hidden library opens only at midnight and trades secrets for years.',
        'ONGOING',
        40,
        false,
        true,
        now() - interval '7 days',
        56000,
        1800,
        now() - interval '45 days',
        now() - interval '1 days',
        now() - interval '40 days'
    ),
    (
        gen_random_uuid(),
        'glass-harbor',
        'Glass Harbor',
        'https://cdn.example.com/covers/glass-harbor.jpg',
        'Quang Vu',
        'A coastal city of crystal hides a storm that never ends.',
        'COMPLETED',
        120,
        false,
        false,
        null,
        210000,
        7600,
        now() - interval '400 days',
        now() - interval '300 days',
        now() - interval '380 days'
    ),
    (
        gen_random_uuid(),
        'ember-road',
        'Ember Road',
        'https://cdn.example.com/covers/ember-road.jpg',
        'Thao Pham',
        'Two couriers race along a burning trade route to save their village.',
        'ONGOING',
        33,
        true,
        false,
        null,
        44000,
        950,
        now() - interval '25 days',
        now() - interval '1 days',
        now() - interval '22 days'
    ),
    (
        gen_random_uuid(),
        'jade-fox-court',
        'Jade Fox Court',
        'https://cdn.example.com/covers/jade-fox-court.jpg',
        'Ha Nguyen',
        'A clever fox spirit navigates a royal court of masked magicians.',
        'ONGOING',
        61,
        false,
        true,
        now() - interval '10 days',
        87000,
        2400,
        now() - interval '120 days',
        now() - interval '1 days',
        now() - interval '110 days'
    ),
    (
        gen_random_uuid(),
        'salt-and-ember',
        'Salt and Ember',
        'https://cdn.example.com/covers/salt-and-ember.jpg',
        'Bao Do',
        'A fire mage and a sea captain hunt a relic beneath storm waters.',
        'PAUSED',
        27,
        false,
        false,
        null,
        32000,
        780,
        now() - interval '70 days',
        now() - interval '20 days',
        now() - interval '65 days'
    ),
    (
        gen_random_uuid(),
        'paper-kite-siege',
        'Paper Kite Siege',
        'https://cdn.example.com/covers/paper-kite-siege.jpg',
        'Tuan Bui',
        'Engineers weaponize kite fleets to defend a mountain citadel.',
        'ONGOING',
        48,
        true,
        true,
        now() - interval '2 days',
        134000,
        5200,
        now() - interval '80 days',
        now() - interval '1 days',
        now() - interval '75 days'
    ),
    (
        gen_random_uuid(),
        'ashen-river',
        'Ashen River',
        'https://cdn.example.com/covers/ashen-river.jpg',
        'Khanh Le',
        'A cursed river carries memories instead of water.',
        'DROPPED',
        18,
        false,
        false,
        null,
        15000,
        400,
        now() - interval '200 days',
        now() - interval '150 days',
        now() - interval '190 days'
    ),
    (
        gen_random_uuid(),
        'crane-and-thunder',
        'Crane and Thunder',
        'https://cdn.example.com/covers/crane-and-thunder.jpg',
        'Vy Ho',
        'A monk and a thief steal a storm drum from a sky temple.',
        'ONGOING',
        66,
        true,
        false,
        null,
        99000,
        3100,
        now() - interval '150 days',
        now() - interval '1 days',
        now() - interval '140 days'
    ),
    (
        gen_random_uuid(),
        'lanterns-of-dawn',
        'Lanterns of Dawn',
        'https://cdn.example.com/covers/lanterns-of-dawn.jpg',
        'My Linh',
        'Every sunrise, a lantern chooses a new guardian for the city.',
        'COMPLETED',
        95,
        false,
        true,
        now() - interval '30 days',
        188000,
        6900,
        now() - interval '500 days',
        now() - interval '350 days',
        now() - interval '480 days'
    ),
    (
        gen_random_uuid(),
        'silver-market',
        'Silver Market',
        'https://cdn.example.com/covers/silver-market.jpg',
        'Tien Phan',
        'A night market trades in luck, and a girl sells her last year.',
        'ONGOING',
        52,
        false,
        false,
        null,
        61000,
        1600,
        now() - interval '110 days',
        now() - interval '3 days',
        now() - interval '105 days'
    ),
    (
        gen_random_uuid(),
        'hollow-banyan',
        'Hollow Banyan',
        'https://cdn.example.com/covers/hollow-banyan.jpg',
        'Nam Tran',
        'A village tree holds the spirits of a forgotten dynasty.',
        'ONGOING',
        58,
        true,
        false,
        null,
        74000,
        2200,
        now() - interval '95 days',
        now() - interval '2 days',
        now() - interval '90 days'
    ),
    (
        gen_random_uuid(),
        'sky-forge',
        'Sky Forge',
        'https://cdn.example.com/covers/sky-forge.jpg',
        'Quyen Vo',
        'A blacksmith climbs floating islands to forge a blade of light.',
        'ONGOING',
        44,
        false,
        true,
        now() - interval '5 days',
        83000,
        2700,
        now() - interval '130 days',
        now() - interval '1 days',
        now() - interval '120 days'
    ),
    (
        gen_random_uuid(),
        'clockwork-orchid',
        'Clockwork Orchid',
        'https://cdn.example.com/covers/clockwork-orchid.jpg',
        'Hien Vu',
        'A botanist builds a mechanical flower that predicts disasters.',
        'COMPLETED',
        88,
        false,
        false,
        null,
        156000,
        5400,
        now() - interval '600 days',
        now() - interval '420 days',
        now() - interval '580 days'
    );
